import { loginPage, registrationPage } from "@/helperVarsAndFunctions/pageUrls"
import Head from "next/head"
import Link from "next/link"
import globalStyle from "../styles/Global.module.css"
import style from "../styles/EntryPage.module.css"
import { useEffect } from "react"

export async function verifyLogin() {
  try {
    const apiResponse = await fetch('/api/delete-user', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({})
    })

  } catch (error) {
    console.error((error as Error).message)
  }
}
async function formSubmitFunction() {
  verifyLogin()
}

export default function Home() {
  useEffect(() => {
    formSubmitFunction()
    localStorage.clear() // If user directs back to entry page through url, makes sure all details are wiped from localStorage
  }, [])

  return (
    <>
      <Head>
        <title>Onboarding Quiz Manager</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <div className={style.entryPageButtonContainer} data-testid="EntryComponent">
          <Link className={globalStyle.buttonStyling} href={registrationPage}>Register</Link>
          <Link className={globalStyle.buttonStyling} href={loginPage}>Login</Link>
        </div>
      </main>
    </>
  )
}
