name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  # building artifacts and running unit tests
  build-and-unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Optimising commands for pipeline
      run: npm ci # Provides faster and consistent builds in automated environments

    - name: Build files
      run: npm run build --if-present # building artifacts

    - name: Run unit tests
      run: npm test # Running unit tests

    - name: Security audit on package dependencies
      run: npm audit --production --audit-level=moderate # Running security audit on dependencies

  # End to end testing stage
  cypress-e2e-test-run:
    runs-on: ubuntu-latest
    needs: build-and-unit-tests
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write the cypress.env.json file
        run: |
          echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.env.json

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm run dev

  # Deploying to Vercel
  deploy-to-production:
    runs-on: ubuntu-latest
    needs: cypress-e2e-test-run
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel environment info
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
